#!/bin/sh

bspc config border_width        1
bspc config window_gap         15
bspc config top_padding        12
bspc config left_padding       -1
bspc config right_padding      -1
bspc config bottom_padding     -3

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d I II III IV V VI VII VIII IX X

sxhkd &
feh --bg-scale ~/images/wallpaper.jpg
compton &
~/src/dotfiles/bin/panel.sh &
