set wildignore+=app/templates_c/**,src/Techo/LegacyBundle/Resources/eocene/templates_c/**,src/Techo/LegacyBundle/Resources/eocene/log/**,vendor/**,app/cache/**,app/logs/**

" Mappings para ejecutar las pruebas de todo el archivo o únicamente aquella
" sobre la cual está el cursor
nm ñra :!phpunit -c app %<cr>
nm ñro :exe '!phpunit -c app --filter ' . cfi#get_func_name() . '$ %'<cr>
