set wildignore+=app/templates_c/**,eocene/templates_c/**,symfony/vendor/**,symfony/app/cache/**,symfony/app/logs/**

" Mappings para ejecutar las pruebas de todo el archivo o únicamente aquella
" sobre la cual está el cursor
nm ñra :!phpunit -c symfony/app %<cr>
nm ñro :exe '!phpunit -c symfony/app --filter ' . cfi#get_func_name() . ' %'<cr>
